---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: hello-world
spec:
  encryptedData:
    tunnel-token: AgA+KXsNTfuvWVImOuXw9/CrWA33mO+vgqODvcK+lglNh57HOfFLe/6Dk+0RIXTcqwHivcN28vdsCpq25/nb3yVtYjrt6aX8KZKvEqmKdWJ1/DS8/KdiagyEiYAz8ihjKcnTdVjIfAeTBdQTyeiKU8fE+cqS37vb5XJTI1sNDzpIUasIT7IcQW+cpElqoB6toHMZPI7R9cArFxfM8EHg+wzoJB7t0Sg1G1vflVMMI978t0FU4S/p7flg9rlU9xu1GBG4yQbV0jXauNLgwvBnyedaWExl/tjd9UZbM+vyRBXM89ER6EToEC8Dc+fFBx/cTcEcTInYjfwRNqf5F2s/33h7W5GD0oJupZsoUWZQVo78T+yvNHYK5k0mEfkg3HHFuJkAGTQhXkgzNf0tq4/3ylEhhcCmoPcFWbQV2mVXuOH/K5haW1Dd7xzPHQLY2OA3Ioiix3/RhKiz7yPAfeMfLgaNC6HoOPL6v8y8lS41QE3UnHnmFq/8zO3aoDXn6vOqw4yUmmVgPD6XmQTcVfLVcqQX6JgMapI/14XvSoA/7/LOo6zyPMenGqLug/WbtZPd+anHlBvl38rul5zPF+JwpA4imrybj7RsPJcH8NA8eVM/8SzvNypIuUzh9hMUyr5HDNuOBS7gkzwCmbRYdpZwyuoA71OpVT3tmfUElmK+2HXXkyt6b4nFrW6ntTNTH8U20Xd/rhXy2qlovZv28UmILLcfNPL2Oebrl4FjKuvud64eMzM/EoRzWe4DVPgAgP/j7s+aAZK627ifg8yJe6jawxJk99q/x5o8Jb3HiX7bZOrRjaLZdztvhu4jGPyGrMOll1XIdjTR7yo8ETa6yKeY7GrIp077EoqvLvBb1n7JklW7v7Uu2roWsWvNNxJyef+yvvm3nwRl7pp0M1dT9hxEjXNQYnQukFPbzPj5v83twzUUdDurkM/hjiDN
  template:
    metadata:
      name: cloudflared-credentials
      namespace: hello-world
    type: Opaque
