---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: couchdb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    tunnel-token: AgBF+Da+Krah9jW95X46ZZgOpxL5dY14E9f0uhd8qbzboBH1ryOcdmxIqi8jIS30dAieBXFhbE+0Eo3mE2xIiT5HUrpBHivpf7/egU4918RafRNj1KURmCeTplFbV/lvYNjJ9YqO3uoRlOTPv+Yf/Bo00uu2ZuDbfhQPICU3ye/fej1qLSlZ5KTbmimQeImud5DRF6K3BPE8jAq7/Gc/SnIfPezfnIG+3AyQsLczllusvXPneyw0tWX4uB5LrlxAMyP+mXwE0tYM81w1QWONX1UStZauMpAJtAD4AGnASvawCXUgbNcGURy67XSw6VmD37OMyCXP3xElh3mjoXadrnM0l4HILQczDvabFO6efVVrMw0chiy4iN7kGYXmpvyfppNR4N5wWPHUofwMZuILjy+pO/esUNeFv4Imil+FO/jxEFGgDjjw63ZBG30FrPdvNX1HTslbggPKeGdJqwnQPa6yabplS78M8mVrm+ew+TQL593M1AfJd2gIN5fnXih+JLoyVh7sqa+WL2zfOF+nu0LREhjAH+SAjODJ/z7xGq7Qer6dcRB1aC4BjVHyQNryhE9s2WRXL4ucOQhYfSdKk1fDsNH5ZAA8DXQJ/cLndF81CGdFBYU5+jIxoJttrBDXhRJ3LM1pNlv+AKYOYf3USkrITUlrVDMIvHFY9bmeNQe7CcZuYsh2EhPQqWe8ML09HLE=
  template:
    metadata:
      name: cloudflared-credentials
      namespace: couchdb
    type: Opaque
