---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: couchdb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    tunnel-token: AgCpt1dXaNTkyfzIQjNIJlCzqQMHQ84jBRqulnRnBNHqU5pS5s8Unr+nTE4E+Avy9TstE91unGO3mbXugbEeuVOs88zDR7HKzlzKuOcq/PhWWVtEPDqeOJyUpXCqMdki7MtSF5LNpOfZ+iMs80/Xn8JBE6B3KswP1hUAPsTVCqQc1FmQMMjbVZaxhSCu8o26KPyZRlLF6eLpZrjsIYjTkryR2YYNmCQurqLR5CyMlGVFo0lz3n4gAdIczMGmFOSuwTh2ylbpW9yNXYv2XPwgQGlBmU8d7LmMKneQYKAp0ReTtSHJAsTSZ5RHLwP7t2NMaEoUzmUspJfYo2g1lIT2CFREm09Hs7NcEGLPQmlk+ey074FYKQYvhs8DeTywcsaEprkUDJRrlo0yhtt5islmaX2w4PksA5Wi1AWO+gwCdJH0j7Aw467+2swMe+EJtYb0UaKGD9TidrJs27obis2BENlewYVYG58TmTFzPXwFEgRKz/yuoTwW1ebOA7hcU8f+iEywcZrc2/FXTbEIuEL/lbR+GAzt8xgadDSYyqq+GwgF5DbOqh5vOroSEIBbzBKl72dgqHS/fvaJp15EzoMNQcL4o0al0GyWfBldJ3XjelHgUUQfdHQYZrsH1xI2x0QA2SDiizj+tSz4BfiAPctd+BfSyO+5eqN24fH8K43l5etvNc1jE0G64hkOQZ9Gfsn8mQJUshhFNzo79DxfNCokaFVlWtF5rhx7oZRhOm3btn4h58jxVgiMNT7XFW74ewF4mg0wsF6SxCYvA6A7Xy2KWNGr2KeXLJ0sCmjjoyb95+iIZPmmQMdPrWxPLohT6Yaf8+q3Vdc9a18Q1YTfIv26C2t/Ws8yQvDW83YDs5rXBznxlZO/sjBLHn0lNvBmkcWKX1JOQnr586DHM6pgAP7Pl4aPaLHNvVy7u4E6DGQQ3Y2EbTZGeLixlOd5
  template:
    metadata:
      name: cloudflared-credentials
      namespace: couchdb
    type: Opaque
