---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    admin-password: AgCmeVGPTydlSjS3gmLcGmJZXtuWFRzzQkKqv+Ha+ybLVuCP4ZgJ7SwPhNy3JhI3vuszRG2X392KqPj26rwMh/KtSCqLUY8TDf8IdGGYcgQNAwRwiCvq53QyxqtpK34XPtNW3/i/ByVquywJJt8yD384B1EOQwpFhBjDsHZEzTJwUed55kDvsUgtBlx+vhqFwv7ewgPlD25MaZvWQZ8TGbUsPp3Bjj7f9zC+X10hbMd6QqISimYmSkoMmdkopbjBNUsn6wyulnNjFIROY9KACAfso+i0VT45PYJW3iNUwng7BQqhKIdAvR9utshDrMKszvcjfaHvWDpXdXUQxtr9qsG4Y82A5KhCYCd26gPpbG9W5KLygl3fUSd0IWU43CDs5IfOCJc6mnk3/CHRinR2xE1Z5A5eZIGYqsPvXf/3cmQVKX+FJNaNzCiL1M/FrcU31z/yz892fQ/n9+USobbTVRsLzChJYwrF09PQmQrDKuJ8gbKxWdbyohaJTH4oXiLGqQIT7g9KpCm+k5oNAs6hfgYSrJ6VKPPtvcRGG2Q8hq23qFgFhhE3N0WNphx7PW2vRZtN3VOSeOosJxB4WolKG36TQmgLPQgaeOkZ8lW7lEVvgfpY6XrYQNnzqvf6FHzBtU1OcvogT0YBQmDQ+j7V2hO9Y3BylhEvZE87eK/7cdj8vrA/xVd7CeD5hNS4rpADz/8eGdh/2b1wNDLjDUCyO68jBNIW
    admin-user: AgC1tXbm3BiLpJb5dHqONiiR59C3Rqgv2uV83Tzwni3f88B3FzC/FuB1Ec6BPxuBb/Yw9K3CCP5zGM6Yr2efgUZc9a876XtSyJrb12Y3Vij2tJvPEfD6UaIvk0bnSRt84T0h/ZBJWGJ9FpBznPhGP0Lf1/yj9Rs2M5DkDECgJNmN2+MYD8k1dck8OGfjjkV857LqZnUzoeKCrHHofZFSU9eFKpwtHyVPAvFfpf7XBmCcJLz10GOwG1wK9RroLZEBuuI8PWNZGpQlC5Z9NWNMak9Q7hGuiqRph8Y6ELouj5Ea9UZG7gFOUaAsKQ7UPQPdBLHjQ0geA5eW266mXGS0+Lp/TDfDbj9b7vmepyGBAHTmV78+kkv+xUPHdHhS1H1AkzenlbApxPtLobRPYXzCy8LupfW13UnOpQOwy4W+soneHDim+lVZBJSFxIhlSYhhSnk0fn1GoY1mQwQn1KDHRY+1CpKEFu4Fs7r/lAAIP2ZCJhKUsFSXfZNMBQS/1qPM7tpYtb/A1Pw94LW3v5KhXos0KjTnL86f8Sm9epiXg9LEoi+DQPaAf8fnkS3rLrlKTeWoyqE+aknjTmzSAMV5kzCTbnsi1XN/vajoRYlkL0gW9wAa7psB2gAE2Qikq/uiW7G4KuQB3pvCgZt7XcSQz6hf7l9fXoBteFPqhtkd63ZdOuz0zFFgVINVA29kPrBtqiUw8JfmtQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
