---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgCM3MOJMQ2MFPTKWvwg3Ij1iJ75zB6Ize1vWRMs42jw1wRmsaJJUbX2gFA8CVj08smevGJ+QwjnYMmDSWPzl7QSMBWXm7BFLu9kfHI20FAc+fLdqUxRrmXPoFg8FUlIBgqbmBAvTpgfMEdXw/kOCU1WSrFcyW5kZbftJVVMknagyqyGlF+9F/Lqyq+Hu0pD2JOfHgPMx9wqjINRLkMCBUktXJ51RTZ7D5p3wLntYCpz+6kbv+4kEJaSIUQVfw/eHSEempf2l1oskoOl2ZIKUJn7FzzltIOmqLxgg27Pf1/UJm08ETv7sZbGe3D+6Z6iJ6u1t1+GsHz1z08Wmzsc4bsyMokXDdoFdUkXvUE4aEk2MLfGeaMdL0VQCp3l90QbS9IJRpKg7rRROk9kHpIUZ2Gho1gVzKtzp6D9VaZxkVTtHRJ7ojA4xZROJ4ZvLOywOtIEAN96ZUqCmsNj9PtU/dJqoprxB66wNO5SSJblEK/4fNhQcYNp002fVENe3fmKHzKGgHR4oHT/FRzulM5a/Clz+QaNvARWyWgty5Pj19HjSr8ZQr4aqSz7ZwYL5oooYJbnelSn3UTZC+8TZKPreYVTXi8P7sxn0v1Adu/7cRXVxFUG3jPRf1X3UbJIDqVJytu2Nyp1Y7UiZqISDs14UKiG9xUoR/A6kiYtYuszkV9vL/FyPsK6wnrGBvIIFvx4XSZcN3k++RXWMrm9lCHauDfSYWObDOOxTppP2GvP3iwf6jJrvUJyF7nWmNcckdFbcAa9HJgoxbWBqHokPHyiHzkHD6jELT/0SFJT2mgstg9kXJs=
  template:
    metadata:
      name: slack-webhook
      namespace: monitoring
    type: Opaque
