---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-password
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgCkzI2AWYd1BLSw3sF2Q7REswTozvxcl1ZmmzCmUHmaYmiPI1ToG3oDSfGltbk7A9LRA4lLlWc8fQnCXGwMxK5utkfyYXuaw1ykAmkvlyr4AS4Fe/rB/wxpKPKLywtwfy3Y/mNT+OUm0OZvdOlEwVKcVrgO372dRGeKHCeYFumbFPOFl4Z8YwSmqhEJg/jRRWBkKyznNqhRf2/hXnxU0iuKpvh348u1c0Wp192xGlvDa3WFc3k3RRGjJ6AKZUMftGkrfxWzGUB4PMSMSiIqMdGfzXOZN6sNyF5iw9C3MHNlNayLUMJYORg6Pisp5WCISHmzikeEmSo+BCuws6A5iIiR11H4sr/MSL+/fr44jblBKquUvQJzHGcEZBgWEtYOT0K3Nb6m2rJ9hBQTD405ty0v1teJNNJSVzKiPTuR8rxcVW4Jn54r36A4+GI7RjEbRXbSs0hlt/rvCUJjfd59OtFb/a+FP76Ru3pvJcMfPUbmNRevYZwdXHYTIrIPbhOAmLL4VudK72Kfx7oJDpjZXxMBuCET1F/cLuUDSO2BqsrAAUFfxSDV121IoYIVB344weM+vU0tGJuJL4GlwPBEgdpzhhUR3SRQrBplQ5YzY/M7vQuKe/ysrQIdz4SRTmggg+RPspjrzImaf4Ly1TTAtNjSrR6jscNHZKCfvdgYp3i6bfSVxGskGT6CxIDCbg22XOnTZIarLTuicnEkf/Owc7NSmtIS
  template:
    metadata:
      name: pihole-password
      namespace: pihole
