---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-password
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgB9Ppu8v+eUmz1COiPshgh0cH9TSfJBIsTt3CH8dWLF2ClNG/JRWSADTOS5SBbO8/qCPbxErzByKszRJIcUV0wRbCZ4vkcGpfKS2aa3eQBvyphOoAuYDTqubFujGhzecYZY0tugb+sNs2vo4KgvafysrrVp58HQ0zA4Vc6GoeE2Nzy8ZynsjKZ1xaIOHl54vOXWdN51OW6lT1iT09HtnmcBPPi1L3UDO0ffexUfW6p9+EyiEe+s37wAHdsuBsbVjG0O6Ef4hp4KPulKEL9mrVXZ9hN9zE/63kQvW2L1qlF6N2x39py4aQmOEkP8yrZG2+5rw5adygqvXr5xBIq02ZGIX8PzmqNvroEgIc0jt2K2+dl9zTsSdPxvJxjBCopVxuzOWfve4GpUj5FYEbOo7ezLssZwpbGPAUXWKPY1MpnMNDHZSWB1nMNg5JSonvCNLAzfMvaxmLvZptym0don6O3Q6TLg3qbP6T8LCH+lKi/Myve5ug5vL9Y4tIu532MF1pgFWcPWMFwOMam2UrlUorS8f3R9yLs3jTgs8xkkltk1MvbDBBVKicvutAr3p2qOlo0tFMlt2be+6FuqAe+aoqNyB5v8QO5QRXIMo2h45wtETTHKprkf4duqMGTXBWsX1SOhQPgOC2CNupuY0pJU71K2lkKUi8Mgkums756G79Tvv3fquSBg+naE+o4L14FXEbXOmXDl2ZzfYNoCpxMQH+sHjT0=
  template:
    metadata:
      name: pihole-password
      namespace: pihole
