---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: book-review-publisher-auth
  namespace: book-review-publisher
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    auth-token: AgAv8WAgNfmheut1ZD4IKP/erZmMaxFAYRaiWqR+41dFyPff9pOAzcMxIOmdIW1LMAAa6MCzoHw1zAtMHIRmEVJbzFXklpSgnHL0UX4obKrci9ao2WfY7+/u+vJSZIQzDHOlaljfATZDfZprZNWrSS6im5BQJnsZ5ygak9YZD81w6vHfr5tlKmsh4wz3Wz4tMue7/USrEHTEHaRniT7VM9Ey80iegKzTYjuFDWFI8u76fViz43xUqrO+/zDgZ/+8/iYIsUobAqZVk3UYOHU+JPE3k8BCDs64uLi/jK7Y+eF6AxTD4IFAvr9hmpTcWCtPOKf29iC1252i+aURuG6wqk3T+59cPEHdkDmmIhjxwP2iOIk8XzBQiyFEVLMmMjW2LGN6BZhhKK1gto9fw89QlCTW4WnwdYvZbHzzNAy54k4xcO3jDBYRhimKB7deJxLrOxVJVrw+XxTguqiLbgnbHX8DV/pWBSJEpOgq++P6RFSIZWzzDmVI9OwJzoEBMhxJWZ09M6+Ntgid5xuAUHUP1Lo5r2hzvNbAoNKysD7eU6w92uSY25bK17Mmnh/QP6kILAT8BoiLOb+iv7C0CBIRcaVluQyoknPUnZm7ZCLYvV/HqkHaxgQcKOFkB/9FYeLqPlyWBwITb/v3MEj0po6DiHSJrPbp1BaUyDmExFje13G7oTBQJC81DrRnPimFiSmbi8+7OrUZfcU9x9LVlsnDaui4YA/4ALh/RI4M0kudHvr7W2uzsxXkJ1WHthNPIZLqjrM49bG4GM1bl9hDjjH26Icf
  template:
    metadata:
      name: book-review-publisher-auth
      namespace: book-review-publisher
    type: Opaque
