---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: book-review-publisher-secrets
  namespace: book-review-publisher
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    github-pat: AgDDyBLyDySAj9MPf5ACxZ8qvhNPs39eT6x8MQisvOn+jbS3Vea1BDq+jNb86r3taLxhEjlPOlVK/q5MGK9wg+8lfAkRwgcsilUUIgeJOkj3XQmjngYF9igs0nDyROM1P1AW71Y7Szsod4X6zzeiCFpwrvGXfmFz3khTWxvsMDc8jK8euCTjjohIzsB+BXfQBW/l0QVs3mGX0D+o92SIkqCFpNy1vFi0LRpMz8DNg4EHyUkWaptewbwWzcPi+kTheimpk+q1qilhp9aYp80RC3i4SDHaTapQ41CepvYhxwJwh6bNIi/FrLWyOB4Qgf7rZ5xzgUmuhXgNUHYQNBEiBPe2Kz+M7pqR4Zv222wWV14nC7jOEUNeFpI5JVFPQX8ySJYu3aw1azOFHAwxG6lLyE7/RjeKahgbfTXNnSJur5hdwroGl3cGmC/lyD5kdy1tylRvFbqeoB+3BrC4gW/0DzFyazzxxS+WyBW6zFhZOiboYHLOTqGKuoqMw2wUq8TaZDh+ret++8/RxBZgCSXkIxdkOa7sTQbCSikwNxc3twdEgykELqyueZJPBx3XdEIlM8NYrRfguyT876jJLCX9kGwKwtgw1SChuNFSZ6wl938iCf9dG8eJhmBppk8KUx1MxG68lTmCYxFYYnPfd/B0zMcWdxLvCTVjHdL7Mj3LUakLPF1/FKcySvmlRwE2Mt6nFAlOrLIcp0dyZj9uojtvodJWAqVTgnlWrNgkJ4p1ULH4zQJNL3Yh29mtDyOGBxN847bDhWGWH6I1mCWLP774vkfacoXf5lYs8VIIaJ0DDM3IZlD2d00xY0RuzNeHwVM=
  template:
    metadata:
      name: book-review-publisher-secrets
      namespace: book-review-publisher
