---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgCFitUmpNjOxHm4LADROeX0c7rRtwuI+3Op1URd35Sh16zSR/FB5PVjTHHA7/Ys93u8lZ0dnzRvPyGdTH54D5oxfQ1WKVWj2B3uVKiloexOyJMEvUdW8p1YTPj+HbADXi9enm1ea4wLgHsLkeLpkBLjg3yf00YhRk2Jj75QlBSjx3ICecKOSFXvjaZoIkn7cRFnA7LZZrwLjCWib29Fth8jYrt7/M1IIorKmMtnyIN1tRMB5cqkU2cA+q8MBExax3FzmGBurhUup03VB7IVK9xIhK0WXaj/7yKN2XGOnclr9AM120BgsmNZA8dhw0FnwgTNjFNFyyC7IJzvi28xbAxtDDR0EgmgTHHEhszRKaCloxwGhI8xR47n/PYbmr4MGi6F+uoes0UdndsWjfCaJqNsSEjNUvDqwvrUYEaTZVLMW6sYoaGI9hGPVWngYqVJrXvrmVKkbhxV5zdKcX9t+3lJbFP5fG6BJY3IUOb5vcxAEd3VRVkf4OrZWU+2v/PIfOOqWklatJz7iubD33avaskSk0mQu1b9S67OgXhFaKJtRv1ue7Ez+MteuRAP0Mc0cjunMldb7vgmRBd2VVq8++elcQ6EBThUCinG29Cyj8CJ/ou6qdVeqsv4Voat3CeioxYKxzt2QZkZKFq9zN1dxOlGD3cmSJzB/mh1Y/3MN7yiGyiuK2grVYfeokrdIPm9A8ik5gHgi3tThfseiHgVBi+RzH7ECFzwGM4arXSoVHTsxw==
  template:
    metadata:
      name: datadog-secret
      namespace: datadog
