---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-cluster-agent-token
  namespace: datadog
spec:
  encryptedData:
    token: AgCQt9gceN2iWXTe4YDk8Mna57oUQP/IDTfrZAB9Z4b8tTz1E3LIUj4aZGceGGe7XKioN5fBWxePEN+XPMHn0S4X1MzRH1P+ucUM3wASxdE5J0jcdFe/PGs0KQEJ/Lt0MJs7Pu//P782J9Vozlta1QPWdR7T86EphfBwGrd4U3RN24WctoX0uuoiloSJiyC400c5/ccvCQh6U7pTam3i7X5Gqd+2iyPw2Jh55J7opbRBBd29Vd9BJo0NtSQAxb2cEfN0j0dGAs+Pba5vWRcN+Oe/GnxCg6z8s1MhIJfBwLYCK4hYA1WzkRxk2cOYp06uWTdjsdwsvK1quWBPHTjUctAVKBGpyO/rkOYj/b8gCwpvfn6H1X0YovghhzryCAq9OSHQvR+ZuzisxIK45tnVLn2YiKxux9fnSoSMtE8smQawkESGp0bCt6LotSCboq2P9hN4N2tSWOFmAa2lCIxQK/5kr56tUxMRPwa3dI420fxVS+a0pvw13Eix9VbBrmlnDK0tZsq8VUw2SCY+xFSgEuysw50IimzXTr3gSENKs60kvtjTtttt7aZLngBS7Hut/PeTKSKVfHPbqKcH0SawnGsKMXDW7dZmqKTmjbmja10H+JhN6hQkyFLOJFs2ynvXa3w0A7W+8mtV2LqrBhnhod/TtwQr04h7bi0aVDbnbaqgkTlDj77+1YVhCs/O4FGrYh+DQ1WL1IND3KMrzCW2C6BekJ6hEs483HK2iYh9+Xm78CCLqG22Dfsm9wrBYCXxkhC0apyaiKw6q4Uaf3gi9PnT
  template:
    metadata:
      name: datadog-cluster-agent-token
      namespace: datadog
