---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: lifttrace
spec:
  encryptedData:
    tunnel-token: AgBEhJoFKlxsi14SPylEvl/hbuKAYbSYkrKAaD2Pd7xiXbMRdiomSWGZ39gE4HOjn25XIaF68Qg1QAwSWdOteBugIHwF0d6pW1slMy23XlwkKwXjh0UJ5JYfpW3cRTknnXhoXHAQwnVoqV67HgGCpiVfeWk3cZXK+SQNAAaPzy+oV6i1tikNJxXLqSGISDHlW+rdWxN8OmrhDLraJ5s1atsayTtv9Mf6KIGWHl/SWtMR3lwmbbTHkBZVYoEU4O/ybNwncjKgrlIEI17sH6b1yJ41lIbHTgPzOx/xRxGcr0EChqnxkjAgG0mt3AS9FLTdXfJXzzkME+4kJkqv4C886jNox5mcN9N7+ygSZKeD2iWtApP8WbQ/D4VHeLGKTxQ64uW0wn4QR3mFjUM43ySoUE/pqOwBMRzbgM8IKq7fP4GvomqPh754F6ThHtIcAqH7ImhozbCfG9PN0MK2xqo01cus4qf1oxSnqcS8fcrkihg8/CwLWvQsJof5RTMyi/UwOLVyc5KSPmLVGzMVEh2F4YFxrCq3JlNlKxVF2kzzPMKZultZBDW/z4qo6jmNtBtY723tMIo5CAKXAAiYjzsuBjOmpvuzrGj7RiWoViT5fTqRg87cTbxwHnzq0vRd6r0vwkBiyyVTGQVmAmKLKQLBGsjUG5JXchXxAvisP2qDmYsUL9h56n4LChnVWPr8qnEvJrlpvVKzq3+9z0R9cbr5+Irg4Qzil8vB9IdmtUHSSkrScipBskDEmRioz0Rit0eZKhntp/75eGN33GDOn49GkhY5Y/VtHnmriUycYegup6sbfhLREplW4VF+nesoabuyL4RhZM1GoxIsF/Bu3Kz3RCAgyZN4RefpEB1Z8CL8Zo8A6iMM/ldAxa62/uy/8E9z/+nAD1gmbY1SCKJt8lX9AqeEki62BsBPTIgt7XwNEw2+OpxHkmc=
  template:
    metadata:
      name: cloudflared-credentials
      namespace: lifttrace
