---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lifttrace-secrets
  namespace: lifttrace
spec:
  encryptedData:
    JWT_SECRET: AgC0fevkxQSc2dK3cBP0cY7z9h8PNXsStiDPHDs2odo+rWHy38G2WBkBswYIsgOcJf+65QZOT7WtfxVF2ThiEFgPJ9fC3WsDbmjZuL8lAi9Aaooy/dytXLSnDN4YTDc0FI538HAl64zKur7+R6nplwrKbrbkwwiyeRCAT1x8EPcZIVUGKsWUNJDgf+7jM34sd2HfLMQSjpU4IM3Hq0ZPOhuSV7Th2RGwQtal+8P3dOpMv3sM1CnLd/nVLtbOI3pU0J1Q/ypEhK10zi89kGREOCMdznNXNcpt9pcUYEVU4Gd6YTMGeckYroy5i+5hjpYzTa8ghb0/MLyYu+GCnFpeyzFrP34+6F/eB2UO5xYOuwuZXPx7MhDRQBxnoVlWflUk7rfsSq4ZJZhxhtZpANs6csqNo/YlRGQcRvwSnhzOkeQh3ZfurnIO7YWjchgdbEpiWE4uqkuP+rCIhoqBodH8krOe6ke55SeWvTyow4iQGgU6Fii7CbNoZuar8h76JM+zCyppkUkZmy7XbPJOfGXce1Btupjm5MBHcAu95ZKvKHi3uiNGb3J59qFLdPErePsnvvd7F5aq/NZ7MW50BIGdcffbfE3zWgvxUqOLrjXIrNqQVmBrsadwsAAk4f/JtHLAnNqVhtViGkSZ53flFaOj4JSj3BxGmvbMryqkYD11Zbcg1nsSubXtAqwCxEh/gCQpGxLvufkAbS1sD99uA8m0lcEyJ2F2SCwYL3DcrfmTdB0ip4BQ9kuAixr3icmy54suJvu9bRWAJEocDarG/fXPgquA
  template:
    metadata:
      name: lifttrace-secrets
      namespace: lifttrace
