---
on:
  schedule:
    - cron: "21 6 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/stale.yml@3915b3040bd9335819629478bc809511bc014c67" # v0.12.0
